// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEditor;
using System;


public class SnapTest
{

	private GameObject rootGO;

	private GameObject childA;
	private GameObject childB;

	delegate void SnapUnitTest();


	protected void setUp() {
		rootGO = new GameObject ();
		childA = createGameObjectWithSnappable (rootGO);
		childB = createGameObjectWithSnappable (rootGO);
	}

	protected void tearDown() {
		GameObject.Destroy (rootGO);
		rootGO = null;
		childA = null;
		childB = null;
	}

	public void testAll() {
		try {

		}
		catch(Exception e) {
			Debug.LogError(e);
		}
	}

	public void test(SnapUnitTest test) {
		try {
			setUp();
			test();
		}
		catch(Exception e) {
			Debug.LogError(e);
		} finally {
			tearDown();
		}
	}

	private GameObject createGameObjectWithSnappable(GameObject parent) {
		GameObject child = new GameObject (); 
		GameObject snapChild = new GameObject ();
		snapChild.AddComponent<SnappableComponent> ();
		snapChild.transform.SetParent (child);
		child.transform.SetParent (parent);
		return child;
	}


	// assert code
	void LogSuccess(SnapUnitTest testMethod) {
		Debug.Log (testMethod + " SUCCESS");
	}

	void LogFailure(SnapAssertException exception) {
		Debug.LogError (exception.Message);
	}


	void assert(object expected, object result, SnapUnitTest testMethod) {
		if (expected != result) {
			throw new SnapAssertException(testMethod.ToString() + " FAILED expected: " + expected + " actual: " + result);
		}
	}

	class SnapAssertException : Exception {
		SnapAssertException(string msg) : base(msg) {}
	}
}


